services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    networks:
      - app-net

  nodeapp:
    build: ./app
    container_name: nodeapp
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:example@mongodb:27017/userdb?authSource=admin
    ports:
      - "3000:3000"
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
    driver: bridge
