services:
  mongodb:
    image: mongo:7
    container_name: mongodb2
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - mongo-data2:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express2
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb2:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8082:8081"
    networks:
      - mongo-network
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mongo-network


  nodeapp:
    build: ./app
    container_name: nodeapp
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:password@mongodb2:27017/userdb?authSource=admin
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    networks:
      - mongo-network

volumes:
  mongo-data2:
  redis-data:

networks:
  mongo-network:
    driver: bridge
